#!/usr/bin/env ruby
base = File.expand_path(File.dirname(__FILE__))
$:.unshift(base)
$:.unshift(base + "/lib")

require 'notify'
include Notify 

if ARGV.length == 0
  puts "Usage: ./run <repository name>"
  puts "Example: ./run prod"
  exit 1
end



repo = get_repo(ARGV[0])

checkout(repo)

passed, failed = run_commands(repo)

generate_report(repo, base, passed, failed)

handle_alert(repo, base, passed, failed)

clean_up(repo)

