#!/usr/bin/env ruby
base = File.expand_path(File.dirname(__FILE__))
lib_path = File.join(base, 'lib')
$:.unshift lib_path

require 'cmd'
require 'notify'

include Notify 

cmd = CommandLine.new
cmd.addParameter('repository', 'name of the repository listed in the configuration to be used')
cmd.process

begin 
  repo = get_repo(cmd.parameters[0])
  
  checkout(repo)
  
  results = run_commands(repo, lib_path)
  
  generate_report(repo, base, results)
  
  handle_alert(repo, base, results)
  
  clean_up(repo)
rescue RuntimeError => error
  puts "RuntimeError caught"
  puts error
  send_error(repo, base, error)
end  

