repositories:
  prod:
    url: git://github.com/byronsalty/simple-notify.git
    checkout-to: /tmp/sn
    type: git
    commands: examples/commands/
    alert: byron@saltylabs.com,someone.else@saltylabs.com
    system-alert: byron@saltylabs.com
    subject: Prod failures
  local:
    url: /home/bsalty/projects/simple-notify
    checkout-to: /tmp/sn-local
    type: git
    commands: examples/commands/
    alert: byron@saltylabs.com
    subject: Testing failures
    report-to: /var/www/local-out
    report-url: http://localhost/local-out
